# Generated by Django 2.2.3 on 2019-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190727_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.URLField(default='https://www.info-computer.com/blog/wp-content/uploads/2018/04/fotoinicio.jpg', max_length=255),
        ),
    ]
