# Generated by Django 2.2.3 on 2019-07-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categoria_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='web',
        ),
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.URLField(blank=True, default='https://www.uic.mx/posgrados/files/2018/05/default-user.png', max_length=255, null=True),
        ),
    ]
