# Generated by Django 2.2.3 on 2019-07-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190729_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.URLField(blank=True, default='https://www.uic.mx/posgrados/files/2018/05/default-user.png', max_length=355, null=True),
        ),
    ]
