# Generated by Django 2.2.3 on 2019-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190729_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='imagen',
            new_name='foto',
        ),
        migrations.AddField(
            model_name='autor',
            name='fondo',
            field=models.URLField(blank=True, default='https://sc2.elpais.com.uy/files/article_default_content/uploads/2017/11/27/5a1c86989e3eb.jpeg', max_length=355, null=True),
        ),
    ]
